version: "3"
services:
    web:
        build: .
        ports:
            - "80:80"
        restart: always
        env_file:
            - .env
        volumes:
            - ./flask.sqlite:/efrastories/flask.sqlite